### ISSUE TITLE
Errors using bower install

### ISSUE THREAD

**Issue by webthingee** [Lullabot/copelandia#11]
~/Sites/lullabot/arts/copelandia/clients/angularjs (master): sudo npm install && bower install
bower cloning git://github.com/angular/bower-angular-resource.git
bower cloning git://github.com/kriskowal/es5-shim
bower cached git://github.com/angular/bower-angular-resource.git
bower fetching angular-resource
bower cached git://github.com/kriskowal/es5-shim
bower fetching es5-shim
bower cloning git://github.com/angular/bower-angular.git
bower cloning git://github.com/angular/bower-angular-cookies.git
bower cached git://github.com/angular/bower-angular.git
bower fetching angular
bower cached git://github.com/angular/bower-angular-cookies.git
bower fetching angular-cookies
bower cloning git://github.com/bestiejs/json3.git
bower error status code of git: 255

There were errors, here's a summary of them:
- angular status code of git: 255

**Comment by sirkitree** [comment]
I removed my angularjs dir, reset (which gave me a clean client) and then ran this and it worked as expected. So I can't seem to reproduce.

I have npm version 1.2.2 (which shouldn't make much difference) & bower version 0.7.0

**Comment by webthingee** [comment]
Looks like I needed to run the install commands in sudo

~$ sudp npm install && sudo bower install --dev

That appeared to help the rest of the process install properly.
