### ISSUE TITLE
Moving client/angularjs to leverage ZURB not TWITTER

### ISSUE THREAD

**Issue by webthingee** [Lullabot/copelandia#12]
It's so much better... any objections to making this change?

I plan to use a slightly different directory structure, but the info http://pburke.de/yeoman-foundation-sass-luv/ is very valid.

**Comment by sirkitree** [comment]
No objections.

**Comment by micahgodbolt** [comment]
Plus Plus ++ all the things!

**Comment by webthingee** [comment]
![Screenshot_4_23_13_2_47_PM](https://f.cloud.github.com/assets/481373/417206/6b113c52-ac5f-11e2-8456-635c095d623e.png)

**Comment by sirkitree** [comment]
Thanks, but ... now my shit's all broken.
![Foundation 4 2013-04-23 16-34-28](https://f.cloud.github.com/assets/28543/417369/f66d4b96-ac65-11e2-82a4-f8eb3ed66fdb.jpg)

**Comment by sirkitree** [comment]
Had to do a gem install zurb-foundation. someone neglected to mention that. updated the readme.

**Comment by webthingee** [comment]
Argh, for some reason I was thinking that it would get it because it was in the require in the Gruntfile.js.
Sry Team :(

**Comment by webthingee** [comment]
Zurb needs jquery to work properly (the script functions at least)
`<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>`

that is only IF we want to use any of the scripts..

**Comment by sirkitree** [comment]
Yeah I was a little shocked at the amount of scripts you added with zurb, especially when they all err out. Let's remove those until/if we actually need them.

**Comment by micahgodbolt** [comment]
as we are moving the prototyping into the angular folder we won't be needing to use zurb (we're building up the framework as we go). So i've removed the files and requirements.

**Comment by webthingee** [comment]
bummer, would have been nice to leave it in there as it provided some extra stuff to work with as we learn angular, seems silly to create an extra branch just to have zurb available.  Also would provide as a good guide for things we would want to implement into the wireframing.

**Comment by webthingee** [comment]
there appears to be some issues...
![image](https://f.cloud.github.com/assets/481373/419946/1efa37be-ace2-11e2-9db9-6bcc704c9f27.png)

**Comment by webthingee** [comment]
Updated readme.
Someone should do a fresh install, on a machine without gems to see if we are all clear.

**Comment by webthingee** [comment]
@micahgodbolt Gruntfile.js, linking to config.rb... love it!!

**Comment by webthingee** [comment]
Grunt provides testing... is there a way to write a test for checking this??? hmmm..... I have never worked with tests, would be a fun hangout problem to solve... @sirkitree ??

**Comment by sirkitree** [comment]
The testing (afaik) is limited to what is in the code base. Seeing as gems are a component that is installed on a particular system, I don't know if we can really 'test' for them. I think we just need to modify our install instructions to include whatever gems we're using and keep it up to date.
