### ISSUE TITLE
Sharing data-binding between two includes, not an easy task...

### ISSUE THREAD

**Issue by webthingee** [Lullabot/copelandia#15]
https://github.com/angular/angular.js/wiki/The-Nuances-of-Scope-Prototypal-Inheritance

**Comment by webthingee** [comment]
I think this is still an issue, as the sharing of scope between ng-includes exists.

**Comment by sirkitree** [comment]
I'm not sure this is really a problem with $scope so much as the controller. you may just need to specify the controller inline with ng-controller

**Comment by micahgodbolt** [comment]
@webthingee is the filter not workign for you with the most recent code pull? (master branch now). It was workign for me last night.

**Comment by webthingee** [comment]
@micahgodbolt latest pull, I see it now, working...
