### ISSUE TITLE
Scss files: New Location

### ISSUE THREAD

**Issue by webthingee** [Lullabot/copelandia#16]
One of the issues we talk about is the 'presentation' folder, when grunt creates a 'build', it would be nice to do one of two things.
1. build so the scss file is not included in the 'dist' folder.  so that if you are using the files in that folder for perhaps a phonegap app, you would be able to have only the files you need in that folder... which scss files are not in that category.
2. move the scss files out of the app directory manually, and still compile the css in the app folder.

**Comment by micahgodbolt** [comment]
I'm a fan of 1. I think moving the scss outside of the app folder moves us too far outside of a normal file structure. We should try to mimick our typical structure as much as possible so that new people coming into any project will always know where things are.

**Comment by webthingee** [comment]
I like that also, just not sure if it is possible... or what it might take to adjust the 'grunt' command that compiles the project.
