### ISSUE TITLE
susy not found

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/copelandia#17]
I've followed the directions and installed susy and sass-globbing but am still getting an error.
### install messages:

```
$ sudo gem install susy
Password:
Successfully installed susy-1.0.8
1 gem installed
Installing ri documentation for susy-1.0.8...
Installing RDoc documentation for susy-1.0.8...

$ sudo gem install sass-globbing
Password:
Successfully installed sass-globbing-1.0.0
1 gem installed
Installing ri documentation for sass-globbing-1.0.0...
Installing RDoc documentation for sass-globbing-1.0.0...
```
### error message

![Red Robot Cafe 2013-04-24 08-41-35](https://f.cloud.github.com/assets/28543/420352/108e9f70-aced-11e2-87f8-0fc3a58d301c.jpg)

What should I do?

**Comment by webthingee** [comment]
and that was after the compiler re-ran?
change the order of the @import, to see if it's only a suzy issue (config.rb)

**Comment by sirkitree** [comment]
Actually, after pulling, installing gems, and re-running grunt server it said there was nothing to compile :frowning: 

```
Running "compass:server" (compass) task
Nothing to compile. If you're trying to start a new project, you have left off the directory argument.
Run "compass -h" to get help.
```

**Comment by micahgodbolt** [comment]
I was struggling getting this to work right as well. The challenge was setting up a .config.rb file instead of declaring all of our compass info in the gruntfile.js

This is the tutorial I followed.

http://ericdfields.com/post/installing-compass-frameworks-in-a-yeoman-project

**Comment by sirkitree** [comment]
~~Ok, so I see that you told the gruntfile to look to the config.rb, but where did you commit the config.rb?~~
nevermind i see it. hrm

**Comment by micahgodbolt** [comment]
@sirkitree ++

**Comment by sirkitree** [comment]
From what I've read you've set this up correctly, but it's still not finding it on my system. I've verified that it's installed on my system in `/Library/Ruby/Gems/1.8/gems` and the system should have access to it. Stupid Ruby Gems.

**Comment by micahgodbolt** [comment]
WHY YOU RUNNING RUBY 1.8!!!!!!!!!!

No clue if it would make a difference, but try upgrading to 1.9.3.

**Comment by sirkitree** [comment]
Another symptom: running `compass watch` within the angularjs folder does nothing. Does that work for you guys?

**Comment by micahgodbolt** [comment]
"Running "compass:server" (compass) task" issue is fixed. There are 2 different tasks that grunt runs, one for a server configuration, one for dist (distribution?). Anyway, I added the config file to the compass:server settings as well, so you shouldn't be getting errors on that saying there aren't any files.

**Comment by sirkitree** [comment]
that totally fixed it.
