### ISSUE TITLE
Testing out a repeat directive for protobots

### ISSUE THREAD

**Issue by webthingee** [Lullabot/copelandia#19]

**Comment by webthingee** [comment]
http://localhost:9000/#/prototest @micahgodbolt

**Comment by webthingee** [comment]
```
<repeat-ntimes repeat="4">
    <h1>Header 1</h1>
    <p>This is the paragraph.</p>
  </repeat-ntimes>
  <hr/>
  <repeat-ntimes repeat="3">
    <p>Lucas ipsum sit amet darth biggs skywalker binks darth jade yavin darth moff jango. Utapau yoda darth yoda coruscant darth dooku. Mace jade solo qui-gon lando vader droid. Ben chewbacca skywalker droid owen. Qui-gon fett hutt sidious palpatine.</p>
  </repeat-ntimes>
```

**Comment by sirkitree** [comment]
I made a change to this that we discussed in the commit. See https://github.com/Lullabot/copelandia/commit/12dd022a967fff9d990c50a5bda81b00cc103878

So now instead of using `<repeat-ntimes repeat="N">` you can use `<ANYTAG data-proto-repeat="N">` to iterate the clone the contents N times.

**Comment by sirkitree** [comment]
If there are any further changes please re-open.

**Comment by webthingee** [comment]
Let's look at the pros for a custom element.

Something about using the div, on an element that you are intending to replace (strip out) seems like it could be improved and accomplished and be more elegant to me by being clearly a replacement/todo indicator.

This would allow one to write all of the necessary html inside of the directive, and very clearly see that it is a place holder.  Conversely, seeing a long line of HTML code with divs, the ability to quickly identify these `<div data-xyz="5">` could/would get lost amongst all of the divs, where as `<proto-repeat="4">` seems like it would server as a clear indication that HERE DUDE, THERE"S SOMETHING TO DO.

:)

**Comment by sirkitree** [comment]
Good points, all.

I suppose if you're looking at this as something _only_ prototypers would utilize vs. something we'd actually use in production, it makes sense. I'm trying, but I can't really think of a use case in which we'd actually want to use this in production either, since anything in production would most likely be wired up to data and therefor utilize ng-repeat. Can you think of any such instance?

**Comment by webthingee** [comment]
Pro HTML DIV tag...
. ajax or javascript into a pre-defined space/spaces.

Perhaps a grid that we would need to place content into an existing space.
Perhaps pre-defined tab markup that could auto create several Ul LI DIV structures for a quick ajax.
