### ISSUE TITLE
Recipe View

### ISSUE THREAD

**Issue by webthingee** [Lullabot/copelandia#20]
Created the routes and updated some resources to pass paramaters to the route, via the url, updated some of the controllers so we have the ability to see individual recipes.

**Comment by webthingee** [comment]
April 26th commits.

**Comment by webthingee** [comment]
left the console log active, maybe @micahgodbolt wants to peak at the array :D see what we may want on the page initially.   More Partials w00t!

**Comment by micahgodbolt** [comment]
Taking a look! Been out of the loop on this project for far too long (by this i mean or 3 or 4 days)

**Comment by webthingee** [comment]
The values form the current json process return wrapped in quotation marks.
I believe we should be using jsonp, or perhaps this restws stuf is just adding too many hoops to jump through.

**Comment by sirkitree** [comment]
JSON notation requires quotes on strings. This has nothing to do with restws (though I think we have services in place now?)
