### ISSUE TITLE
Implement Dynamic Routing

### ISSUE THREAD

**Issue by micahgodbolt** [Lullabot/copelandia#21]
As per http://gregorypratt.github.io/AngularDynamicRouting/

**Comment by webthingee** [comment]
Looks really interesting! nice find Micah!

**Comment by micahgodbolt** [comment]
this has been merged.

**Comment by webthingee** [comment]
I don't think this is working.
Any url points to blank.html

**Comment by webthingee** [comment]
Finding more about it here.. http://stackoverflow.com/questions/13681116/angularjs-dynamic-routing

**Comment by webthingee** [comment]
Looks like it was just some path issues..
please check and pull :dancers: 
https://github.com/Lullabot/copelandia/pull/28

**Comment by micahgodbolt** [comment]
Yup, go go committing new errors!
