### ISSUE TITLE
Let authenticated users submit recipes

### ISSUE THREAD

**Issue by juampynr** [Lullabot/copelandia#24]
Once a user has registered, he should have an area where he can manage his recipes and submit new ones.

**Comment by micahgodbolt** [comment]
I love this idea. Curious to see how authentication works in this type of setup.

**Comment by juampynr** [comment]
Will keep you updated! Need to figure out how to authenticate users first. We may need to write our first bundle (exciting!)

**Comment by juampynr** [comment]
Anonymous users from the Symfony site can now submit recipes. This was done at https://github.com/Lullabot/copelandia-symfony/issues/6.

Closing.
