### ISSUE TITLE
Page Routing Issue

### ISSUE THREAD

**Issue by webthingee** [Lullabot/copelandia#27]
After the dynamic routing.
https://github.com/Lullabot/copelandia/pull/22

the routing of individual nodes/pages appears to be broken.

**Comment by micahgodbolt** [comment]
It was working fine for me. Let me take a look tonight.

**Comment by webthingee** [comment]
looks like the partial is missing... hmmm

**Comment by webthingee** [comment]
ok, the template changed names, and moved locations.
not sure what the thinking is here as for when it's in /partial and when it's not...
confusing as I think of this as the 'content' of the page, which seems like a partial, I know we talked about leaving them in the root, but I think it's confusing as I am hands on with it right now.

I'll update the paths.

**Comment by webthingee** [comment]
new layout looks good.
