### ISSUE TITLE
Configure Solr

### ISSUE THREAD

**Issue by juampynr** [Lullabot/copelandia#29]
So things such as searching can be done easily and fast by clients.

**Comment by makangus** [comment]
Do we need @bchavet's help on this?

**Comment by juampynr** [comment]
I need him first for https://github.com/Lullabot/copelandia-symfony/issues/4. Will harass him today :japanese_ogre:

**Comment by bchavet** [comment]
New solr index is available for copelandia at http://ops.lullabot.com:8983/copelandia.lulladev.com (only accessible internally on linode)
