### ISSUE TITLE
Question about RestWS

### ISSUE THREAD

**Issue by alnutile** [Lullabot/copelandia#38]
I noticed upon install that to get the local client (Angular.js) to work I still had to enable the RestWS module.
I assume since Services is there that maybe this project is using that now and not RestWS?

Thanks

**Comment by sirkitree** [comment]
We started out with restws, but I'm unsure of where we were in converting to Services. For recent projects we've actually started using @justafish's [CreateAPI](https://drupal.org/project/createapi) instead.

If any work were to happen in this project around the mechanism for creating the json feeds, I'd prefer to see restws and services taken out and CreateAPI used instead.
