### ISSUE TITLE
Cookbook Filter

### ISSUE THREAD

**Issue by webthingee** [Lullabot/copelandia#7]
Mimic effect of the shake shack location&menu slider menu.

**Comment by sirkitree** [comment]
What the heck are you talking about? lol

**Comment by webthingee** [comment]
This was a note from a conversation with Josh... he wants to implement a menu like on http://www.shakeshack.com/
if you click on location&menu

**Comment by sirkitree** [comment]
Interesting!

I guess I would term that as navigation, not filtering since it doesn't actually filter anything on the page, but actually takes you to a section of the site.
