### ISSUE TITLE
Scaffolding out the Recipe Display

### ISSUE THREAD

**Issue by webthingee** [Lullabot/copelandia#8]

**Comment by micahgodbolt** [comment]
Let's scaffold this out in the Angular wireframe, not the ruby one.

**Comment by micahgodbolt** [comment]
@joshriggs It looks like we're properly moved over to prototyping in angular. I think in the long run, angular is going to be much easier to set up, understand and use. We have a recipe display already set up with some basic layout. If you have further ideas as to how it should be laid out, I can give you a quick tour of angular sometime.

**Comment by joshriggs** [comment]
@micahgodbolt  So, Protobots is done for? Let's catch up via hangout later this week.

**Comment by micahgodbolt** [comment]
Not really 'done for', just evolving :) It might be done for as a ruby project. It's just that Angular lets us do pretty much everything Ruby was lettings us do, and it appears to be even more flexible when creating custom code.
